### ISSUE TITLE
The openmp error

### ISSUE THREAD

**Issue by wxmwy** [ziqin/ShengBTE#1]
I think your code will get error Vp_plus and Vp_minus. The sum of Vp_plus should not in parallel.

    complex(kind=8) :: Vp_plus_all(Ntri)
    Vp_plus=0.d0
    !$OMP PARALLEL DO 
    do ll=1,Ntri
       prefactor=1.d0/sqrt(masses(types(Index_i(ll)))*&
            masses(types(Index_j(ll)))*masses(types(Index_k(ll))))*&
            phexp(dot_product(realqprime,R_j(:,ll)))*&
            phexp(-dot_product(realqdprime,R_k(:,ll)))
       Vp0=0.d0
       do rr=1,3
          do ss=1,3
             do tt=1,3
                Vp0=Vp0+Phi(tt,ss,rr,ll)*&
                     eigenvect(q,i,tt+3*(Index_i(ll)-1))*&
                     eigenvect(qprime,j,ss+3*(Index_j(ll)-1))*&
                     conjg(eigenvect(qdprime,k,rr+3*(Index_k(ll)-1)))
             end do
          end do
       end do
       Vp_plus_all(ll)=prefactor*Vp0
    end do
    !$OMP END PARALLEL DO
    Vp_plus=sum(Vp_plus_all)

**Comment by ziqin** [comment]
I think you are right.
